--- 
title: "Learning R for Clinical Trial Data"
author: "Maya Gans"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "A gentle introduction to R for the Cytel staff."
---

# Preface

This book is geared towards people who are bravely taking the step towards learning R but have yet to even download R on their local machines. 

## The book will walk you through:

 - Getting R Set up on your computer
 - Understanding the RStudio IDE
 - Using the RStudio IDE
 - A gentle introduction to R
 - Importing and viewing data
 - Manipulating data
 - Visualizing data
 - Use the generated tables and plots to create a report
 
# Getting Set Up with R

## Setup instructions
R and RStudio are separate downloads and installations. R is the underlying statistical computing environment, but using R alone is no fun. RStudio is a graphical integrated development environment (IDE) that makes using R much easier and more interactive. You need to install R before you install RStudio. After installing both programs, you will need to install the `tidyverse` and `haven` packages from within RStudio. Follow the instructions below for your operating system, and then follow the instructions to install `tidyverse` and `haven`.

### Windows
If you already have R and RStudio installed
Open RStudio, and click on “Help” > “Check for updates”. If a new version is available, quit RStudio, and download the latest version for RStudio.
To check which version of R you are using, start RStudio and the first thing that appears in the console indicates the version of R you are running. Alternatively, you can type sessionInfo(), which will also display which version of R you are running. Go on the CRAN website and check whether a more recent version is available. If so, please download and install it. You can check here for more information on how to remove old versions from your system if you wish to do so.

If you don’t have R and RStudio installed:

 - Download R from the CRAN website.
 - Run the .exe file that was just downloaded
 - Go to the RStudio download page
 - Under Installers select RStudio x.yy.zzz - Windows Vista/7/8/10 (where x, y, and z represent version numbers)
 - Double click the file to install it

Once it’s installed, open RStudio to make sure it works and you don’t get any error messages.

### macOS

If you already have R and RStudio installed
Open RStudio, and click on “Help” > “Check for updates”. If a new version is available, quit RStudio, and download the latest version for RStudio.

To check the version of R you are using, start RStudio and the first thing that appears on the terminal indicates the version of R you are running. Alternatively, you can type sessionInfo(), which will also display which version of R you are running. Go on the CRAN website and check whether a more recent version is available. If so, please download and install it.

If you don’t have R and RStudio installed:

 - Download R from the CRAN website.
 - Select the .pkg file for the latest R version
 - Double click on the downloaded file to install R
 - It is also a good idea to install XQuartz (needed by some packages)
 - Go to the RStudio download page
 - Under Installers select RStudio x.yy.zzz - Mac OS X 10.6+ (64-bit) (where x, y, and z represent version numbers)
 - Double click the file to install RStudio

Once it’s installed, open RStudio to make sure it works and you don’t get any error messages.

## Linux

Follow the instructions for your distribution from CRAN, they provide information to get the most recent version of R for common distributions. For most distributions, you could use your package manager (e.g., for Debian/Ubuntu run sudo apt-get install r-base, and for Fedora sudo yum install R), but we don’t recommend this approach as the versions provided by this are usually out of date. In any case, make sure you have at least R 3.3.1.

 - Go to the RStudio download page
 - Under Installers select the version that matches your distribution, and install it with your preferred method (e.g., with Debian/Ubuntu sudo dpkg -i rstudio-x.yy.zzz-amd64.deb at the terminal).
 - Once it’s installed, open RStudio to make sure it works and you don’t get any error messages.

## For everyone
After installing R and RStudio, you need to install the `tidyverse` and `haven` packages.

After starting RStudio, at the console type: 

```
install.packages(c("tidyverse", "haven"))
```

You can also do this by going to Tools -> Install Packages and typing the names of the packages separated by a comma.
